//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LillyScan.Backend.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LillyScan.Backend.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [[Layer]]
        ///[type]
        ///InputLayer
        ///[name]
        ///input_1
        ///[config]
        ///{&apos;batch_input_shape&apos;: (None, 256, 256, 1), &apos;dtype&apos;: &apos;float64&apos;, &apos;sparse&apos;: False, &apos;ragged&apos;: False, &apos;name&apos;: &apos;input_1&apos;}
        ///[weight_shapes]
        ///0
        ///[[Layer]]
        ///[type]
        ///Conv2D
        ///[name]
        ///conv2d
        ///[config]
        ///{&apos;name&apos;: &apos;conv2d&apos;, &apos;dtype&apos;: &apos;float64&apos;, &apos;filters&apos;: 16, &apos;kernel_size&apos;: (3, 3), &apos;strides&apos;: (1, 1), &apos;padding&apos;: &apos;same&apos;, &apos;data_format&apos;: &apos;channels_last&apos;, &apos;dilation_rate&apos;: (1, 1), &apos;groups&apos;: 1, &apos;activation&apos;: &apos;linear&apos;, &apos;use_bias&apos;: True}
        ///[inputs]
        ///input_1
        ///[weight_shapes]
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string model_segm {
            get {
                return ResourceManager.GetString("model_segm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] seg_model {
            get {
                object obj = ResourceManager.GetObject("seg_model", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] seg_model_64 {
            get {
                object obj = ResourceManager.GetObject("seg_model_64", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
